const ForumActionTypes = {
  UPDATE_FORUMS: 'UPDATE_FORUMS',
  UPDATE_FORUM_COMMENTS: 'UPDATE_FORUM_COMMENTS',
  UPDATE_FORUM_VIEWS: 'UPDATE_FORUM_VIEWS',
  UPDATE_TRENDING_TOPICS: 'UPDATE_TRENDING_TOPICS',
};

export default ForumActionTypes;
