const BlogActionTypes = {
  UPDATE_CATEGORIES: 'UPDATE_CATEGORIES',
  UPDATE_BLOG_COMMENTS: 'UPDATE_BLOG_COMMENTS',
  UPDATE_BLOG_VIEWS: 'UPDATE_BLOG_VIEWS',
  SET_CURRENT_READING: 'SET_CURRENT_READING',
};

export default BlogActionTypes;
